#Tests derived from this base work with the following data:
#	- 1    Reference genome file
#	- 1-2  Input Read / Query files (input for mapper)
#	- 1    Comparison file containing the *expected* mapping output

base: base
is_basic: Yes

pipeline:
   init:
     - init

   main:
     - map
     - sort_prepare
     - calc_stats

   report_overview:
     - report_overview

   report_detail:
     - report_detail

   cleanup:
     - cleanup

#################################################################################
#################################################################################

title: A Basic Simulated Mapping Test
description: "Maps simulated data, computes and visualizes mapping statistics"

input_info:
  simulator: Unknown
  platform: Unknown
  read_length: Unknown
  read_count: Unknown
  divergence: Unknown

report:
  mapq_overview_steps: [0] #[0,5,10,15,20,25,30,40,50,60,70,80,90,100,110,120,130,140,150,170,190,210,225,250]

#################################################################################
#################################################################################

#Default parameters specific to base_mapping

#Statistics configuration
#Maximum position distance of a mapping relative to the one in input:mapping_comparison to be considered correct
pos_threshold: 50

#Evaluate for RNA mapping (split alignments)
evaluate_rna: No

#Mapper output file config
#Exact filename determined by name of executing mapper
#Usually not needed to be changed
output:
   #Will make the mapper output in BAM format if set to true
   #However, BAM output will be converted back to SAM before comparison due to technical reasons (BAM index required by PySAM for reading but only possible by chromosome pos)
   bam: No
   bam_workaround: Yes

   mapping_prefix: out_
   #mapping_extension: #Set based on config value "bam"

   #Does testee output mapping need to be sorted?
   should_sort_testee: Yes

#################################################################################
#################################################################################
input:
   #Reference genome file (relative to working directory)
   reference: reference.fasta

   #Input read files (relative to working directory)
   reads:
   - reads.fastq

   #Is the input (single or multiple files) comprised of paired end reads?
   reads_paired_end: No

   #Reference output file to compare to (relative to working directory)
   mapping_comparison: mapping_comparison.sam

   #Does in_mapping_comparison need to be sorted?
   should_sort_comparison: Yes

   #When comparison is sorted, overwrite the original with the sorted version
   sort_in_place: Yes

   #See BAM problem in output section, this option only affects testing if the mapping comparison
   #format is BAM
   bam_workaround: Yes

params:
  ngm: {}