base: base_mapping
is_basic: Yes

pipeline:
   init:
     - base_mapping/init

   main:
     - base_mapping/map
     - base_mapping/sort_prepare
     - base_mapping/calc_stats
     - base_mapping/calc_time

   report_overview:
     - report_overview

   report_detail:
     - report_detail

   cleanup:
     - base_mapping/cleanup

#################################################################################
#################################################################################

title: A Basic Real Mapping Test
description: "Maps read data, computes and visualizes mapping statistics without evaluating alignment correctness"

#################################################################################
#################################################################################

evaluation:
   class: lib.evaluator.BasicEvaluatorSAM
